Repository Likelion-at-SMWU-12th/DreamPatissier-Client, pull requests merged in 2024-07, with the labels that each got.

#1 MenuBar 기본 구현 (Nav)
  dream/package-lock.json
  dream/package.json
  dream/public/index.html
  dream/src/App.js
  dream/src/assets/logo.png
  dream/src/components/Button.jsx
  dream/src/index.js
  dream/src/pages/Bakery.js
  dream/src/pages/Diary.js
  dream/src/pages/Menubar.js
  dream/src/pages/Recipes.js
  dream/src/styles/Menubar.css
  dream/yarn.lock
Labels: 🔨 기능개발, 🎨 스타일 수정

#2 마이페이지 레이아웃 완성
  dream/src/App.js
  dream/src/assets/advertise.png
  dream/src/assets/myprofile.png
  dream/src/pages/Bakery.js
  dream/src/pages/Diary.js
  dream/src/pages/Menubar.js
  dream/src/pages/Recipes.js
  dream/src/pages/Users.js
  dream/src/pages/userpage/OfUse.js
  dream/src/pages/userpage/Order.js
  dream/src/pages/userpage/Review.js
  dream/src/pages/userpage/SavedRecipes.js
  dream/src/pages/userpage/TestBread.js
  dream/src/styles/Users.css
Labels: 🔨 기능개발, 🎨 스타일 수정

#17 Hyeonseo
  dream/src/assets/bread_stamp.png
  dream/src/pages/Diary.js
  dream/src/styles/Diary.css
Labels: 🐞 버그 수정, 🔨 기능개발, 🎨 스타일 수정

#19 [빵기록] 기본 UI 완성 (최종 미완성)
  dream/package-lock.json
  dream/package.json
  dream/src/App.js
  dream/src/assets/baguette.png
  dream/src/assets/bread_stamp.png
  dream/src/assets/picture_button.png
  dream/src/pages/Diary.js
  dream/src/pages/diary/RecordDetail.js
  dream/src/pages/mockApi.js
  dream/src/styles/Diary.css
  dream/src/styles/RecordDetail.css
  dream/yarn.lock
  node_modules/.yarn-integrity
  yarn.lock
Labels: 🐞 버그 수정, 🔨 기능개발, 🎨 스타일 수정

#23 레시피 파트 UI 및 일부 기능 구현
  dream/db.json
  dream/package.json
  dream/public/images/bread_re.png
  dream/src/App.js
  dream/src/assets/delete-icon.png
  dream/src/assets/edit-icon.png
  dream/src/assets/saved-icon.png
  dream/src/assets/unsaved-icon.png
  dream/src/pages/Diary.js
  dream/src/pages/Recipes.js
  dream/src/pages/diary/RecordDetail.js
  dream/src/pages/recipes/EditRecipe.js
  dream/src/pages/recipes/WriteRecipe.js
  dream/src/pages/recipes/init_recipe_image.png
  dream/src/pages/recipes/represent_picture.png
  dream/src/styles/Recipes.css
  dream/src/styles/WriteRecipe.css
Labels: 🐞 버그 수정, 🔨 기능개발, 🎨 스타일 수정, 🔗 API 연결

#25 회원가입 / 로그인 화면 관련 세부 기능
  dream/src/App.js
  dream/src/assets/cansee.svg
  dream/src/assets/delpassword.svg
  dream/src/assets/nosee.svg
  dream/src/components/Button.jsx
  dream/src/components/CheckBox.jsx
  dream/src/components/Popup.jsx
  dream/src/components/SignForm.jsx
  dream/src/components/YellowBtn.jsx
  dream/src/pages/accounts/Login.js
  dream/src/pages/accounts/SignClear.js
  dream/src/pages/accounts/Signup.js
  dream/src/pages/accounts/TermP.js
  dream/src/pages/accounts/TermS.js
  dream/src/pages/userpage/OfUse.js
  dream/src/styles/SignForm.css
Labels: 🔨 기능개발, 🎨 스타일 수정

#26 결과 페이지 UI / 폰트,사진 추가 / 유형테스트 관련 수정 / 검색결과 X 페이지
  dream/src/assets/TE-plant.png
  dream/src/assets/test-bagle.png
  dream/src/assets/test-baguette.png
  dream/src/assets/test-cake.png
  dream/src/assets/test-plain.png
  dream/src/assets/warning.png
  dream/src/components/ProgressBar.jsx
  dream/src/components/Question.jsx
  dream/src/components/Result.jsx
  dream/src/fonts/NotoSansKR-Bold.woff
  dream/src/fonts/NotoSansKR-Medium.woff
  dream/src/fonts/NotoSansKR-Regular.woff
  dream/src/index.js
  dream/src/pages/SearchPage.js
  dream/src/pages/userpage/TestBread.js
  dream/src/styles/Font.css
Labels: 🐞 버그 수정, 🔨 기능개발, 🎨 스타일 수정

#28 상세페이지 UI + 자잘한 오류 수정
  dream/src/App.js
  dream/src/assets/shoppingcart.svg
  dream/src/components/Product.jsx
  dream/src/components/Search.jsx
  dream/src/pages/Bakery.js
  dream/src/pages/CategoryPage.js
  dream/src/pages/Detail.js
  dream/src/pages/SearchPage.js
  dream/src/pages/userpage/TestBread.js
  dream/src/styles/Menubar.css
Labels: 🐞 버그 수정, 🔨 기능개발, 🎨 스타일 수정

#29 장바구니 페이지 UI 완성 / 기타 등등 css 기능 오류 수정 / 결제 페이지 틀잡기
  dream/src/App.js
  dream/src/components/Category.jsx
  dream/src/components/CheckBox.jsx
  dream/src/components/Product.jsx
  dream/src/components/Search.jsx
  dream/src/components/SignForm.jsx
  dream/src/components/YellowBtn.jsx
  dream/src/pages/Bakery.js
  dream/src/pages/Cart.js
  dream/src/pages/Detail.js
  dream/src/pages/Menubar.js
  dream/src/pages/Order.js
  dream/src/pages/Users.js
  dream/src/pages/accounts/Login.js
  dream/src/pages/accounts/Signup.js
  dream/src/styles/Menubar.css
  dream/src/styles/SignForm.css
Labels: 🐞 버그 수정, 🔨 기능개발, 🎨 스타일 수정

#31 결제페이지/결제성공페이지 UI, 유형테스트 임시데이터 연결해보기
  dream/public/images/TE-plant.png
  dream/public/images/test-bagle.png
  dream/public/images/test-baguette.png
  dream/public/images/test-cake.png
  dream/public/images/test-plain.png
  dream/public/test.json
  dream/src/App.js
  dream/src/assets/kakaopay.png
  dream/src/assets/npay.png
  dream/src/assets/tosspay.png
  dream/src/components/Result.jsx
  dream/src/pages/Detail.js
  dream/src/pages/Menubar.js
  dream/src/pages/Order.js
  dream/src/pages/OrderClear.js
  dream/src/pages/Users.js
  dream/src/pages/userpage/TestBread.js
Labels: 🔨 기능개발, 🎨 스타일 수정

#33 JSON 서버 대신에 백 주소 기입
  dream/src/App.js
  dream/src/assets/picture_button.png
  dream/src/assets/timer2.png
  dream/src/assets/tool2.png
  dream/src/pages/Diary.js
  dream/src/pages/diary/WriteRecord.js
  dream/src/pages/recipes/EditRecipe.js
  dream/src/pages/recipes/WriteRecipe.js
  dream/src/pages/review/WriteReview.js
  dream/src/pages/userpage/OrderList.js
  dream/src/pages/userpage/Review.js
  dream/src/pages/userpage/SavedRecipes.js
  dream/src/styles/RecordDetail.css
  dream/src/styles/SavedRecipes.css
  dream/src/styles/WriteRecipe.css
Labels: 🔨 기능개발, 🎨 스타일 수정, 🔗 API 연결

#35 회원가입/로그인 깨진 CSS 수정 + signupclear 수정
  dream/src/components/CheckBox.jsx
  dream/src/components/SignForm.jsx
  dream/src/pages/accounts/Login.js
  dream/src/pages/accounts/SignClear.js
  dream/src/pages/accounts/Signup.js
Labels: 🐞 버그 수정, 🎨 스타일 수정, 🔗 API 연결
